// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUhpLMLKMpwIDhSYtFhy9s6ksa8NxL9GE',
    appId: '1:493935587050:web:4d1a20ee7ed0dd4f2d3193',
    messagingSenderId: '493935587050',
    projectId: 'message-board-46a03',
    authDomain: 'message-board-46a03.firebaseapp.com',
    storageBucket: 'message-board-46a03.firebasestorage.app',
    measurementId: 'G-RL5W1H5YG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK0o0cm_ZbBiqt6Y5PDGdLkND0_yXQG-k',
    appId: '1:493935587050:android:1b665a6f4662636b2d3193',
    messagingSenderId: '493935587050',
    projectId: 'message-board-46a03',
    storageBucket: 'message-board-46a03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9m8kVKGT4NlvfQWhV76w5Mjv4EnyZIY',
    appId: '1:493935587050:ios:53a0b7325d8a73f52d3193',
    messagingSenderId: '493935587050',
    projectId: 'message-board-46a03',
    storageBucket: 'message-board-46a03.firebasestorage.app',
    iosBundleId: 'com.example.hw2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ9m8kVKGT4NlvfQWhV76w5Mjv4EnyZIY',
    appId: '1:493935587050:ios:53a0b7325d8a73f52d3193',
    messagingSenderId: '493935587050',
    projectId: 'message-board-46a03',
    storageBucket: 'message-board-46a03.firebasestorage.app',
    iosBundleId: 'com.example.hw2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUhpLMLKMpwIDhSYtFhy9s6ksa8NxL9GE',
    appId: '1:493935587050:web:b13cfd959ab732e92d3193',
    messagingSenderId: '493935587050',
    projectId: 'message-board-46a03',
    authDomain: 'message-board-46a03.firebaseapp.com',
    storageBucket: 'message-board-46a03.firebasestorage.app',
    measurementId: 'G-16V0EPPYQ1',
  );
}
